/**
 * FS-OCR Api
 * The API Backend for the FS-OCR App.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PlaylistMatrixRow { 
    one?: number;
    two?: number;
    three?: number;
    four?: number;
    five?: number;
    six?: number;
    seven?: number;
    eight?: number;
    nine?: number;
    ten?: number;
}
