/**
 * FS-OCR Api
 * The API Backend for the FS-OCR App.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {PlaylistMatrixRow} from './playlistMatrixRow';


export interface PlaylistMatrix { 
    first?: PlaylistMatrixRow;
    second?: PlaylistMatrixRow;
    third?: PlaylistMatrixRow;
    fourth?: PlaylistMatrixRow;
    fifth?: PlaylistMatrixRow;
}
