/**
 * FS-OCR Api
 * The API Backend for the FS-OCR App.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface User { 
    id?: number;
    mail: string;
    password?: string;
    age?: number;
    gender?: User.GenderEnum;
    netto_income?: number;
    current_shares?: number;
    current_bonds?: number;
    pension_age?: number;
    coupon?: number;
    inflation?: number;
    expenses?: number;
    personal_status?: string;
    zipcode?: string;
}
export namespace User {
    export type GenderEnum = 'm' | 'f' | 'd';
    export const GenderEnum = {
        M: 'm' as GenderEnum,
        F: 'f' as GenderEnum,
        D: 'd' as GenderEnum
    };
}
