/**
 * FS-OCR Api
 * The API Backend for the FS-OCR App.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {WebhookResources} from './webhookResources';


export interface Webhook { 
    name?: string;
    filterType?: string;
    filterId?: string;
    eventType?: string;
    eventId?: string;
    objectType?: string;
    objectId?: string;
    eventDatetime?: string;
    resources?: WebhookResources;
}
